server:
  port: 8082
spring:
  application:
    name: stripe-payment-provider
  jackson:
    property-naming-strategy: SNAKE_CASE
stripe:
  config:
    mode: payment
    successUrl: http://localhost:3000/payment/success
    cancelUrl: http://localhost:3000/payment/cancel
    createLinkAPI: https://api.stripe.com/v1/checkout/sessions
    expireLinkAPI: https://api.stripe.com/v1/checkout/sessions/%s/expire
    retrieveLinkApi: https://api.stripe.com/v1/checkout/sessions/%s
    secret-key: key